### ISSUE TITLE
Bug: Wallet broken after receiving colored token

### ISSUE THREAD

**Issue by svenger87** [iotaledger/pollen-wallet#2]
I created a colored token on wallet 1. (Name: svenger87, symbol SVG, supply 1000)
Then i sent 10 of these tokens to 2.

In the moment the wallet recognized the incoming transaction the wallet blanked out.
Clearing  C:\Users\$user$\AppData\Roaming\pollen-wallet doesn´t help to fix the issue.

In the startup phase the interface shows up for a millisecond and then gets blank.

![image](https://user-images.githubusercontent.com/35897839/88627241-493e6680-d0ac-11ea-9667-bf822752a3a9.png)

**Comment by obany** [comment]
Thanks for the report, at a quick guess there is a fault with the incoming wallet not recognizing the incoming asset type and falling over.  I will take a look.

**Comment by obany** [comment]
Fixed in https://github.com/iotaledger/pollen-wallet/releases/tag/v0.1.2
