### ISSUE TITLE
Unknown Colored Token

### ISSUE THREAD

**Issue by stricki** [iotaledger/pollen-wallet#4]
I have received 1 colored token to my receive address but the Name and Symbol is not displayed correctly. It says 'Unknown' for the tokenname and an empty string for Symbol.

I have also sent one of my colored token to somebody else's wallet who told me that the token name (Bitcoin) and the symbol (BTC) only appeared after resending the token to the address (which was done by the other user)

Screenshot of my wallet attached
![Screenshot from 2020-07-28 15-34-36](https://user-images.githubusercontent.com/17906700/88672630-f5517300-d0e7-11ea-8d97-2d969d7978ce.png)

**Comment by obany** [comment]
The token asset names are not sent in the transaction payload, eventually there will be a central registry for them. For now you just have to edit the asset it created for you locally to set the name.
