### ISSUE TITLE
Balances aren't showed anymore when reaching Index 20

### ISSUE THREAD

**Issue by NiC0x36** [iotaledger/pollen-wallet#7]
After reaching index 20, due to sending tokens away, my pollen wallet 0.5.0 doesn't show any balances anymore. They are still there, when I check the balance of the Address with index 20 (is receive: yes) over the node though.

Tested on Pollen 0.5.1

![image](https://user-images.githubusercontent.com/15385922/111154351-6cfae200-8593-11eb-9bef-021cdffcc926.png)

**Comment by obany** [comment]
Should be fixed with the latest release https://github.com/iotaledger/pollen-wallet/releases/tag/v0.5.1

**Comment by Travetown** [comment]
Unfortunately, the error also occurs with the current version.

**Comment by obany** [comment]
Another fix in place, could you try this release to see if it fixes the issue https://github.com/iotaledger/pollen-wallet/releases/tag/v0.5.2

**Comment by Travetown** [comment]
with the new version the error seems to have been eliminated.  Many Thanks!
